### ISSUE TITLE
Custom styling not working?

### ISSUE THREAD

**Issue by martimfreitas1** [mythicrp/mythic_notify#1]
I'm trying to make a custom styling notification, I'm using this code:
`exports['mythic_notify']:SendAlert('inform', 'Hype! Custom Styling!', { ['background-color'] = '#ff0000', ['color'] = '#ff0000' })`
And I get the default inform notification.

**Comment by Alzar** [comment]
So when using the export function, you'd have to provide the length parameter if you're wanting to use the custom styling. So if you change it to ;

```LUA
exports['mythic_notify']:SendAlert('inform', 'Hype! Custom Styling', 2500, { ['background-color'] = '#ff0000', ['color'] = '#ff0000')
```

That's my bad, I didn't update the readme part of it after changing the function call.

You can omit adding the length parameter if you use the event due to it being a list and being able to define things out of order;

(This being if you were calling from client ofc, if calling from server need TriggerClientEvent & pass the target source)
```LUA
TriggerEvent('mythic_notify:client:SendAlert', { type = 'inform', text = 'HYPE!', style = { ['background-color'] = '#ff0000', ['color'] = '#ff0000' })
```

Will update the readme to ensure correctness, sorry again!
